ALTER TABLE luna_woocommerce_transfer_queue
    ADD COLUMN locked_at DATETIME NULL AFTER status,
    ADD COLUMN started_at DATETIME NULL AFTER locked_at,
    ADD COLUMN finished_at DATETIME NULL AFTER started_at,
    ADD COLUMN attempts INT UNSIGNED NOT NULL DEFAULT 0 AFTER finished_at,
    ADD COLUMN last_error TEXT NULL AFTER attempts,
    ADD COLUMN last_run_id BIGINT UNSIGNED NULL AFTER last_error,
    ADD INDEX idx_luna_woocommerce_transfer_queue_locked_at (locked_at),
    ADD INDEX idx_luna_woocommerce_transfer_queue_last_run_id (last_run_id);

CREATE TABLE IF NOT EXISTS luna_woocommerce_transfer_runs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT UNSIGNED NULL,
    woocommerce_connection_id BIGINT UNSIGNED NOT NULL,
    queue_id BIGINT UNSIGNED NULL,
    run_type VARCHAR(80) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'pending',
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    source_order_id VARCHAR(80) NULL,
    orders_found INT UNSIGNED NOT NULL DEFAULT 0,
    orders_written INT UNSIGNED NOT NULL DEFAULT 0,
    addresses_written INT UNSIGNED NOT NULL DEFAULT 0,
    items_written INT UNSIGNED NOT NULL DEFAULT 0,
    item_meta_written INT UNSIGNED NOT NULL DEFAULT 0,
    order_meta_written INT UNSIGNED NOT NULL DEFAULT 0,
    refunds_seen INT UNSIGNED NOT NULL DEFAULT 0,
    skipped_count INT UNSIGNED NOT NULL DEFAULT 0,
    error_count INT UNSIGNED NOT NULL DEFAULT 0,
    summary_json LONGTEXT NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_luna_woocommerce_transfer_runs_connection_id (woocommerce_connection_id),
    INDEX idx_luna_woocommerce_transfer_runs_queue_id (queue_id),
    INDEX idx_luna_woocommerce_transfer_runs_status (status),
    INDEX idx_luna_woocommerce_transfer_runs_source_order_id (source_order_id),
    INDEX idx_luna_woocommerce_transfer_runs_started_at (started_at),
    CONSTRAINT fk_luna_woocommerce_transfer_runs_connection
        FOREIGN KEY (woocommerce_connection_id) REFERENCES luna_woocommerce_connections(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_luna_woocommerce_transfer_runs_queue
        FOREIGN KEY (queue_id) REFERENCES luna_woocommerce_transfer_queue(id)
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS luna_woocommerce_order_headers (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT UNSIGNED NULL,
    woocommerce_connection_id BIGINT UNSIGNED NOT NULL,
    source_order_id BIGINT UNSIGNED NOT NULL,
    order_status VARCHAR(80) NULL,
    currency VARCHAR(20) NULL,
    order_type VARCHAR(40) NOT NULL,
    tax_amount DECIMAL(26,8) NULL,
    total_amount DECIMAL(26,8) NULL,
    customer_id BIGINT UNSIGNED NULL,
    billing_email VARCHAR(320) NULL,
    created_at_gmt DATETIME NULL,
    updated_at_gmt DATETIME NULL,
    parent_order_id BIGINT UNSIGNED NULL,
    payment_method VARCHAR(190) NULL,
    payment_method_title TEXT NULL,
    transaction_id VARCHAR(190) NULL,
    customer_ip VARCHAR(100) NULL,
    customer_user_agent TEXT NULL,
    customer_note TEXT NULL,
    created_via VARCHAR(100) NULL,
    source_woocommerce_version VARCHAR(40) NULL,
    prices_include_tax TINYINT(1) NULL,
    coupon_usages_are_counted TINYINT(1) NULL,
    download_permission_granted TINYINT(1) NULL,
    cart_hash VARCHAR(190) NULL,
    new_order_email_sent TINYINT(1) NULL,
    order_key VARCHAR(190) NULL,
    order_stock_reduced TINYINT(1) NULL,
    paid_at_gmt DATETIME NULL,
    completed_at_gmt DATETIME NULL,
    shipping_tax_amount DECIMAL(26,8) NULL,
    shipping_total_amount DECIMAL(26,8) NULL,
    discount_tax_amount DECIMAL(26,8) NULL,
    discount_total_amount DECIMAL(26,8) NULL,
    recorded_sales TINYINT(1) NULL,
    raw_order_json LONGTEXT NULL,
    last_imported_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_luna_woocommerce_order_headers_source (woocommerce_connection_id, source_order_id),
    INDEX idx_luna_woocommerce_order_headers_workspace_id (workspace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS luna_woocommerce_order_addresses (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT UNSIGNED NULL,
    woocommerce_connection_id BIGINT UNSIGNED NOT NULL,
    source_address_id BIGINT UNSIGNED NOT NULL,
    source_order_id BIGINT UNSIGNED NOT NULL,
    address_type VARCHAR(40) NOT NULL,
    first_name TEXT NULL,
    last_name TEXT NULL,
    company TEXT NULL,
    address_1 TEXT NULL,
    address_2 TEXT NULL,
    city TEXT NULL,
    state TEXT NULL,
    postcode TEXT NULL,
    country TEXT NULL,
    email VARCHAR(320) NULL,
    phone VARCHAR(100) NULL,
    last_imported_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_luna_woocommerce_order_addresses_source (woocommerce_connection_id, source_address_id),
    INDEX idx_luna_woocommerce_order_addresses_order (woocommerce_connection_id, source_order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS luna_woocommerce_order_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT UNSIGNED NULL,
    woocommerce_connection_id BIGINT UNSIGNED NOT NULL,
    source_order_item_id BIGINT UNSIGNED NOT NULL,
    source_order_id BIGINT UNSIGNED NOT NULL,
    item_name LONGTEXT NULL,
    item_type VARCHAR(200) NOT NULL,
    product_id BIGINT UNSIGNED NULL,
    variation_id BIGINT UNSIGNED NULL,
    quantity DECIMAL(26,8) NULL,
    line_subtotal DECIMAL(26,8) NULL,
    line_subtotal_tax DECIMAL(26,8) NULL,
    line_total DECIMAL(26,8) NULL,
    line_tax DECIMAL(26,8) NULL,
    tax_class VARCHAR(190) NULL,
    tax_data_raw LONGTEXT NULL,
    last_imported_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_luna_woocommerce_order_items_source (woocommerce_connection_id, source_order_item_id),
    INDEX idx_luna_woocommerce_order_items_order (woocommerce_connection_id, source_order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS luna_woocommerce_order_itemmeta_raw (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT UNSIGNED NULL,
    woocommerce_connection_id BIGINT UNSIGNED NOT NULL,
    source_item_meta_id BIGINT UNSIGNED NOT NULL,
    source_order_item_id BIGINT UNSIGNED NOT NULL,
    source_order_id BIGINT UNSIGNED NOT NULL,
    meta_key VARCHAR(255) NULL,
    meta_value LONGTEXT NULL,
    last_imported_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_luna_woocommerce_order_itemmeta_source (woocommerce_connection_id, source_item_meta_id),
    INDEX idx_luna_woocommerce_order_itemmeta_order (woocommerce_connection_id, source_order_id),
    INDEX idx_luna_woocommerce_order_itemmeta_item (woocommerce_connection_id, source_order_item_id),
    INDEX idx_luna_woocommerce_order_itemmeta_key (meta_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS luna_woocommerce_order_meta_raw (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT UNSIGNED NULL,
    woocommerce_connection_id BIGINT UNSIGNED NOT NULL,
    source_order_meta_id BIGINT UNSIGNED NOT NULL,
    source_order_id BIGINT UNSIGNED NOT NULL,
    meta_key VARCHAR(255) NULL,
    meta_value LONGTEXT NULL,
    last_imported_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_luna_woocommerce_order_meta_source (woocommerce_connection_id, source_order_meta_id),
    INDEX idx_luna_woocommerce_order_meta_order (woocommerce_connection_id, source_order_id),
    INDEX idx_luna_woocommerce_order_meta_key (meta_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
