CREATE TABLE IF NOT EXISTS luna_export_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT UNSIGNED NULL,
    connection_id BIGINT UNSIGNED NULL,
    integration_type VARCHAR(80) NOT NULL,
    profile_key VARCHAR(120) NOT NULL,
    name VARCHAR(190) NOT NULL,
    description TEXT NULL,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    export_format VARCHAR(40) NOT NULL DEFAULT 'json',
    auth_mode VARCHAR(40) NOT NULL DEFAULT 'token_hmac',
    token_hash VARCHAR(255) NULL,
    secret_encrypted TEXT NULL,
    include_raw_meta TINYINT(1) NOT NULL DEFAULT 0,
    include_item_raw_meta TINYINT(1) NOT NULL DEFAULT 0,
    batch_size INT UNSIGNED NOT NULL DEFAULT 100,
    last_successful_export_at DATETIME NULL,
    last_successful_watermark VARCHAR(190) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_luna_export_profiles_workspace_integration_key (workspace_id, integration_type, profile_key),
    INDEX idx_luna_export_profiles_integration_key (integration_type, profile_key),
    INDEX idx_luna_export_profiles_connection (connection_id),
    INDEX idx_luna_export_profiles_enabled (is_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS luna_export_runs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT UNSIGNED NULL,
    export_profile_id BIGINT UNSIGNED NOT NULL,
    integration_type VARCHAR(80) NOT NULL,
    profile_key VARCHAR(120) NOT NULL,
    status VARCHAR(40) NOT NULL,
    triggered_by VARCHAR(40) NOT NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    requested_since DATETIME NULL,
    requested_until DATETIME NULL,
    watermark_before VARCHAR(190) NULL,
    watermark_after VARCHAR(190) NULL,
    records_found INT UNSIGNED NOT NULL DEFAULT 0,
    records_exported INT UNSIGNED NOT NULL DEFAULT 0,
    error_count INT UNSIGNED NOT NULL DEFAULT 0,
    summary_json LONGTEXT NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_luna_export_runs_profile (export_profile_id),
    INDEX idx_luna_export_runs_integration_key (integration_type, profile_key),
    INDEX idx_luna_export_runs_status (status),
    INDEX idx_luna_export_runs_started_at (started_at),
    CONSTRAINT fk_luna_export_runs_profile
        FOREIGN KEY (export_profile_id) REFERENCES luna_export_profiles(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
